
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class UI2 extends javax.swing.JFrame {

    /**
     * Creates new form UI2
     */
    private UnitConverter unitConverter;
    private History history;

    public UI2() {
        initComponents();
        history = new History();
        unitConverter = new UnitConverter() {
            @Override
            public double toBaseUnit(double value, String fromUnit) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public double fromBaseUnit(double value, String toUnit) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBesaranPokok = new javax.swing.JButton();
        btnBesaranTurunan = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        BesaranPokok = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnWaktu = new javax.swing.JButton();
        btnPanjang = new javax.swing.JButton();
        btnMassa = new javax.swing.JButton();
        btnSuhu = new javax.swing.JButton();
        btnKuatArus = new javax.swing.JButton();
        btnIntensitasCahaya = new javax.swing.JButton();
        btnJumlahZat = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        BesaranTurunan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        btnKecepatan = new javax.swing.JButton();
        btnVolume = new javax.swing.JButton();
        btnLuas = new javax.swing.JButton();
        btnMassaJenis = new javax.swing.JButton();
        btnMomentum = new javax.swing.JButton();
        btnTekanan = new javax.swing.JButton();
        btnDaya = new javax.swing.JButton();
        btnPercepatan = new javax.swing.JButton();
        btnGaya = new javax.swing.JButton();
        btnUsaha = new javax.swing.JButton();
        Konversi = new javax.swing.JPanel();
        cbJenis = new javax.swing.JComboBox<>();
        cbSatuan = new javax.swing.JComboBox<>();
        cbSatuan1 = new javax.swing.JComboBox<>();
        cbJenis1 = new javax.swing.JComboBox<>();
        taInput = new javax.swing.JTextField();
        taOutput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        btnKonversi = new javax.swing.JButton();
        btnTukar = new javax.swing.JButton();
        History = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnBack4 = new javax.swing.JButton();

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        Home.setPreferredSize(new java.awt.Dimension(360, 640));
        Home.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        Home.add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 640);

        btnBesaranPokok.setMaximumSize(new java.awt.Dimension(75, 20));
        btnBesaranPokok.setMinimumSize(new java.awt.Dimension(75, 20));
        btnBesaranPokok.setPreferredSize(new java.awt.Dimension(20, 20));
        btnBesaranPokok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBesaranPokokMouseClicked(evt);
            }
        });
        btnBesaranPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBesaranPokokActionPerformed(evt);
            }
        });
        Home.add(btnBesaranPokok);
        btnBesaranPokok.setBounds(40, 330, 120, 130);

        btnBesaranTurunan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBesaranTurunanMouseClicked(evt);
            }
        });
        btnBesaranTurunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBesaranTurunanActionPerformed(evt);
            }
        });
        Home.add(btnBesaranTurunan);
        btnBesaranTurunan.setBounds(200, 330, 130, 130);

        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
        });
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        Home.add(btnHistory);
        btnHistory.setBounds(295, 10, 60, 50);

        getContentPane().add(Home, "card2");

        BesaranPokok.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        BesaranPokok.add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 640);

        btnWaktu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWaktuMouseClicked(evt);
            }
        });
        btnWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWaktuActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnWaktu);
        btnWaktu.setBounds(230, 240, 110, 140);

        btnPanjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanjangMouseClicked(evt);
            }
        });
        btnPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanjangActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnPanjang);
        btnPanjang.setBounds(0, 100, 90, 130);

        btnMassa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMassaMouseClicked(evt);
            }
        });
        btnMassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMassaActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnMassa);
        btnMassa.setBounds(245, 113, 80, 120);

        btnSuhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuhuMouseClicked(evt);
            }
        });
        btnSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuhuActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnSuhu);
        btnSuhu.setBounds(5, 243, 70, 140);

        btnKuatArus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKuatArusMouseClicked(evt);
            }
        });
        btnKuatArus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuatArusActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnKuatArus);
        btnKuatArus.setBounds(5, 393, 100, 140);

        btnIntensitasCahaya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIntensitasCahayaMouseClicked(evt);
            }
        });
        btnIntensitasCahaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntensitasCahayaActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnIntensitasCahaya);
        btnIntensitasCahaya.setBounds(240, 393, 110, 170);

        btnJumlahZat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJumlahZatMouseClicked(evt);
            }
        });
        btnJumlahZat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJumlahZatActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnJumlahZat);
        btnJumlahZat.setBounds(140, 503, 72, 130);

        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        BesaranPokok.add(btnBack);
        btnBack.setBounds(15, 10, 40, 40);

        getContentPane().add(BesaranPokok, "card3");

        BesaranTurunan.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        BesaranTurunan.add(jLabel3);
        jLabel3.setBounds(0, 0, 360, 640);

        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnBack2);
        btnBack2.setBounds(15, 10, 40, 40);

        btnKecepatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKecepatanActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnKecepatan);
        btnKecepatan.setBounds(40, 103, 72, 100);

        btnVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumeActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnVolume);
        btnVolume.setBounds(250, 93, 72, 100);

        btnLuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuasActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnLuas);
        btnLuas.setBounds(250, 203, 90, 100);

        btnMassaJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMassaJenisActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnMassaJenis);
        btnMassaJenis.setBounds(25, 303, 100, 110);

        btnMomentum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMomentumActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnMomentum);
        btnMomentum.setBounds(25, 203, 110, 100);

        btnTekanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTekananActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnTekanan);
        btnTekanan.setBounds(250, 303, 90, 100);

        btnDaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayaActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnDaya);
        btnDaya.setBounds(260, 413, 72, 100);

        btnPercepatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercepatanActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnPercepatan);
        btnPercepatan.setBounds(40, 413, 72, 110);

        btnGaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGayaActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnGaya);
        btnGaya.setBounds(260, 523, 72, 110);

        btnUsaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsahaActionPerformed(evt);
            }
        });
        BesaranTurunan.add(btnUsaha);
        btnUsaha.setBounds(30, 520, 72, 110);

        getContentPane().add(BesaranTurunan, "card4");

        Konversi.setLayout(null);

        cbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisActionPerformed(evt);
            }
        });
        Konversi.add(cbJenis);
        cbJenis.setBounds(0, 160, 160, 22);

        Konversi.add(cbSatuan);
        cbSatuan.setBounds(0, 200, 160, 22);

        Konversi.add(cbSatuan1);
        cbSatuan1.setBounds(200, 200, 160, 22);

        cbJenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenis1ActionPerformed(evt);
            }
        });
        Konversi.add(cbJenis1);
        cbJenis1.setBounds(200, 160, 160, 22);

        taInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        taInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taInputActionPerformed(evt);
            }
        });
        Konversi.add(taInput);
        taInput.setBounds(30, 280, 90, 50);

        taOutput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Konversi.add(taOutput);
        taOutput.setBounds(240, 280, 90, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        Konversi.add(jLabel4);
        jLabel4.setBounds(0, 0, 360, 640);

        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        btnBack3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBack3KeyPressed(evt);
            }
        });
        Konversi.add(btnBack3);
        btnBack3.setBounds(15, 13, 40, 40);

        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        btnKonversi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKonversiKeyPressed(evt);
            }
        });
        Konversi.add(btnKonversi);
        btnKonversi.setBounds(140, 380, 80, 50);

        btnTukar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTukarActionPerformed(evt);
            }
        });
        Konversi.add(btnTukar);
        btnTukar.setBounds(155, 273, 50, 60);

        getContentPane().add(Konversi, "card5");

        History.setOpaque(false);
        History.setLayout(null);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        History.add(btnEdit);
        btnEdit.setBounds(140, 590, 80, 23);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        History.add(btnTambah);
        btnTambah.setBounds(260, 590, 80, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        History.add(btnDelete);
        btnDelete.setBounds(20, 590, 80, 23);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Besaran", "Nilai Input", "Satuan Asal", "Satuan Tujuan", "Hasil Konversi"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setOpaque(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        History.add(jTable1);
        jTable1.setBounds(0, 90, 360, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5.png"))); // NOI18N
        History.add(jLabel5);
        jLabel5.setBounds(0, 0, 360, 640);

        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });
        History.add(btnBack4);
        btnBack4.setBounds(20, 13, 40, 40);

        getContentPane().add(History, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String besaranDipilih;
    private String jenis;

    private void konversiSatuan() {
        try {
            double nilaiInput = Double.parseDouble(taInput.getText());
            String satuanAsal = (String) cbSatuan.getSelectedItem();
            String satuanTujuan = (String) cbSatuan1.getSelectedItem();
            String besaran = besaranDipilih;

            unitConverter = UnitConverterFactory.getConverter(besaran);

            double hasilKonversi = unitConverter.convert(nilaiInput, satuanAsal, satuanTujuan);

            taOutput.setText(String.valueOf(hasilKonversi));
            history.addData(besaran, nilaiInput, satuanAsal, satuanTujuan, hasilKonversi);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Input tidak valid. Harap masukkan angka.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void isiSatuanMetric() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        switch (besaranDipilih) {
            case "Panjang" ->
                tambahItemComboBox(cbSatuan, List.of("Nanometer (nm)", "Micrometer (µm)", "Millimeter (mm)", "Centimeter (cm)", "Meter (m)", "Kilometer (km)"));
            case "Massa" ->
                tambahItemComboBox(cbSatuan, List.of("Milligram (mg)", "Gram (g)", "Kilogram (kg)", "Quintal (q)", "Ton (t)"));
            case "Waktu" ->
                tambahItemComboBox(cbSatuan, List.of("Nanodetik (ns)", "Millidetik (ms)", "Detik (s)", "Menit (min)", "Jam (h)", "Hari (d)"));
            case "Suhu" ->
                tambahItemComboBox(cbSatuan, List.of("Celsius (°C)", "Kelvin (K)", "Reaumur (°Re)"));
            case "Kuat Arus" ->
                tambahItemComboBox(cbSatuan, List.of("Ampere (A)"));
            case "Intensitas Cahaya" ->
                tambahItemComboBox(cbSatuan, List.of("Candela (cd)"));
            case "Jumlah Zat" ->
                tambahItemComboBox(cbSatuan, List.of("Mol (mol)"));

            case "Luas" ->
                tambahItemComboBox(cbSatuan, List.of("Meter Persegi (m²)", "Kilometer Persegi (km²)", "Hektare (ha)"));
            case "Volume" ->
                tambahItemComboBox(cbSatuan, List.of("Milliliter (mL)", "Liter (L)", "Meter Kubik (m³)"));
            case "Massa Jenis" ->
                tambahItemComboBox(cbSatuan, List.of("Gram per Centimeter Kubik (g/cm³)", "Kilogram per Meter Kubik (kg/m³)"));
            case "Kecepatan" ->
                tambahItemComboBox(cbSatuan, List.of("Centimeter per Detik (cm/s)", "Meter per Detik (m/s)", "Kilometer per Jam (km/h)"));
            case "Percepatan" ->
                tambahItemComboBox(cbSatuan, List.of("Meter per Detik Kuadrat (m/s²)", "Gal (Gal)"));
            case "Gaya" ->
                tambahItemComboBox(cbSatuan, List.of("Dyne (dyn)", "Newton (N)", "Kilogram-force (kgf)"));
            case "Usaha" ->
                tambahItemComboBox(cbSatuan, List.of("Calorie (cal)", "Joule (J)", "Kilojoule (kJ)"));
            case "Daya" ->
                tambahItemComboBox(cbSatuan, List.of("Watt (W)", "Kilowatt (kW)", "Megawatt (MW)"));
            case "Tekanan" ->
                tambahItemComboBox(cbSatuan, List.of("Pascal (Pa)", "Kilogram-force per Centimeter Persegi (kgf/cm²)", "Bar (bar)", "Atmosfer Teknis (at)"));
            case "Momentum" ->
                tambahItemComboBox(cbSatuan, List.of("Kilogram Meter per Detik (kg·m/s)", "Newton Second (N·s)"));
        }
    }

    private void isiSatuanImperial() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        switch (besaranDipilih) {
            case "Panjang" ->
                tambahItemComboBox(cbSatuan, List.of("Inch (in)", "Foot (ft)", "Yard (yd)", "Furlong", "Mile (mi)"));
            case "Massa" ->
                tambahItemComboBox(cbSatuan, List.of("Ounce (oz)", "Pound (lb)", "Stone (st)", "Slug"));
            case "Waktu" ->
                tambahItemComboBox(cbSatuan, List.of("Nanodetik (ns)", "Millidetik (ms)", "Detik (s)", "Menit (min)", "Jam (h)", "Hari (d)"));
            case "Suhu" ->
                tambahItemComboBox(cbSatuan, List.of("Fahrenheit (°F)", "Rankine (°R)"));
            case "Kuat Arus" ->
                tambahItemComboBox(cbSatuan, List.of("Ampere (A)"));
            case "Intensitas Cahaya" ->
                tambahItemComboBox(cbSatuan, List.of("Candela (cd)"));
            case "Jumlah Zat" ->
                tambahItemComboBox(cbSatuan, List.of("Mol (mol)"));

            case "Luas" ->
                tambahItemComboBox(cbSatuan, List.of("Square Inch (in²)", "Square Foot (ft²)", "Acre", "Square Mile (mi²)"));
            case "Volume" ->
                tambahItemComboBox(cbSatuan, List.of("Cubic Inch (in³)", "Cubic Foot (ft³)", "Pint", "Gallon (gal)"));
            case "Massa Jenis" ->
                tambahItemComboBox(cbSatuan, List.of("Pound per Cubic Foot (lb/ft³)", "Slug per Cubic Foot (slug/ft³)"));
            case "Kecepatan" ->
                tambahItemComboBox(cbSatuan, List.of("Feet per Second (ft/s)", "Miles per Hour (mph)"));
            case "Percepatan" ->
                tambahItemComboBox(cbSatuan, List.of("Feet per Second Squared (ft/s²)"));
            case "Gaya" ->
                tambahItemComboBox(cbSatuan, List.of("Ounce-force (ozf)", "Pound-force (lbf)"));
            case "Usaha" ->
                tambahItemComboBox(cbSatuan, List.of("Foot-Pound (ft·lb)", "British Thermal Unit (BTU)"));
            case "Daya" ->
                tambahItemComboBox(cbSatuan, List.of("BTU per Hour (BTU/h)", "Horsepower (hp)"));
            case "Tekanan" ->
                tambahItemComboBox(cbSatuan, List.of("Pound per Square Inch (psi)", "Atmosphere (atm)"));
            case "Momentum" ->
                tambahItemComboBox(cbSatuan, List.of("Pound-feet per Second (lb·ft/s)"));
        }

    }

    private void isiSatuanMetricTujuan() {
        switch (besaranDipilih) {
            case "Panjang" ->
                tambahItemComboBox(cbSatuan1, List.of("Nanometer (nm)", "Micrometer (µm)", "Millimeter (mm)", "Centimeter (cm)", "Meter (m)", "Kilometer (km)"));
            case "Massa" ->
                tambahItemComboBox(cbSatuan1, List.of("Milligram (mg)", "Gram (g)", "Kilogram (kg)", "Quintal (q)", "Ton (t)"));
            case "Waktu" ->
                tambahItemComboBox(cbSatuan1, List.of("Nanodetik (ns)", "Millidetik (ms)", "Detik (s)", "Menit (min)", "Jam (h)", "Hari (d)"));
            case "Suhu" ->
                tambahItemComboBox(cbSatuan1, List.of("Celsius (°C)", "Kelvin (K)", "Reaumur (°Re)"));
            case "Kuat Arus" ->
                tambahItemComboBox(cbSatuan1, List.of("Ampere (A)"));
            case "Intensitas Cahaya" ->
                tambahItemComboBox(cbSatuan1, List.of("Candela (cd)"));
            case "Jumlah Zat" ->
                tambahItemComboBox(cbSatuan1, List.of("Mol (mol)"));
            case "Luas" ->
                tambahItemComboBox(cbSatuan1, List.of("Meter Persegi (m²)", "Kilometer Persegi (km²)", "Hektare (ha)"));
            case "Volume" ->
                tambahItemComboBox(cbSatuan1, List.of("Milliliter (mL)", "Liter (L)", "Meter Kubik (m³)"));
            case "Massa Jenis" ->
                tambahItemComboBox(cbSatuan1, List.of("Gram per Centimeter Kubik (g/cm³)", "Kilogram per Meter Kubik (kg/m³)"));
            case "Kecepatan" ->
                tambahItemComboBox(cbSatuan1, List.of("Centimeter per Detik (cm/s)", "Meter per Detik (m/s)", "Kilometer per Jam (km/h)"));
            case "Percepatan" ->
                tambahItemComboBox(cbSatuan1, List.of("Meter per Detik Kuadrat (m/s²)", "Gal (Gal)"));
            case "Gaya" ->
                tambahItemComboBox(cbSatuan1, List.of("Dyne (dyn)", "Newton (N)", "Kilogram-force (kgf)"));
            case "Usaha" ->
                tambahItemComboBox(cbSatuan1, List.of("Calorie (cal)", "Joule (J)", "Kilojoule (kJ)"));
            case "Daya" ->
                tambahItemComboBox(cbSatuan1, List.of("Watt (W)", "Kilowatt (kW)", "Megawatt (MW)"));
            case "Tekanan" ->
                tambahItemComboBox(cbSatuan1, List.of("Pascal (Pa)", "Kilogram-force per Centimeter Persegi (kgf/cm²)", "Bar (bar)", "Atmosfer Teknis (at)"));
            case "Momentum" ->
                tambahItemComboBox(cbSatuan1, List.of("Kilogram Meter per Detik (kg·m/s)", "Newton Second (N·s)"));
        }
    }

    private void isiSatuanImperialTujuan() {
        switch (besaranDipilih) {
            case "Panjang" ->
                tambahItemComboBox(cbSatuan1, List.of("Inch (in)", "Foot (ft)", "Yard (yd)", "Furlong", "Mile (mi)"));
            case "Massa" ->
                tambahItemComboBox(cbSatuan1, List.of("Ounce (oz)", "Pound (lb)", "Stone (st)", "Slug"));
            case "Waktu" ->
                tambahItemComboBox(cbSatuan1, List.of("Nanodetik (ns)", "Millidetik (ms)", "Detik (s)", "Menit (min)", "Jam (h)", "Hari (d)"));
            case "Suhu" ->
                tambahItemComboBox(cbSatuan1, List.of("Fahrenheit (°F)", "Rankine (°R)"));
            case "Kuat Arus" ->
                tambahItemComboBox(cbSatuan1, List.of("Ampere (A)"));
            case "Intensitas Cahaya" ->
                tambahItemComboBox(cbSatuan1, List.of("Candela (cd)"));
            case "Jumlah Zat" ->
                tambahItemComboBox(cbSatuan1, List.of("Mol (mol)"));
            case "Luas" ->
                tambahItemComboBox(cbSatuan1, List.of("Square Inch (in²)", "Square Foot (ft²)", "Acre", "Square Mile (mi²)"));
            case "Volume" ->
                tambahItemComboBox(cbSatuan1, List.of("Cubic Inch (in³)", "Cubic Foot (ft³)", "Pint", "Gallon (gal)"));
            case "Massa Jenis" ->
                tambahItemComboBox(cbSatuan1, List.of("Pound per Cubic Foot (lb/ft³)", "Slug per Cubic Foot (slug/ft³)"));
            case "Kecepatan" ->
                tambahItemComboBox(cbSatuan1, List.of("Feet per Second (ft/s)", "Miles per Hour (mph)"));
            case "Percepatan" ->
                tambahItemComboBox(cbSatuan1, List.of("Feet per Second Squared (ft/s²)"));
            case "Gaya" ->
                tambahItemComboBox(cbSatuan1, List.of("Ounce-force (ozf)", "Pound-force (lbf)"));
            case "Usaha" ->
                tambahItemComboBox(cbSatuan1, List.of("Foot-Pound (ft·lb)", "British Thermal Unit (BTU)"));
            case "Daya" ->
                tambahItemComboBox(cbSatuan1, List.of("BTU per Hour (BTU/h)", "Horsepower (hp)"));
            case "Tekanan" ->
                tambahItemComboBox(cbSatuan1, List.of("Pound per Square Inch (psi)", "Atmosphere (atm)"));
            case "Momentum" ->
                tambahItemComboBox(cbSatuan1, List.of("Pound-feet per Second (lb·ft/s)"));
        }
    }

    private void loadHistoryTable() {
        Object[][] data = history.getTableData();
        String[] columnNames = {"Besaran", "Nilai Input", "Satuan Asal", "Satuan Tujuan", "Hasil Konversi"}; // 5 kolom
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable1.setModel(model);
    }

    private void isi_cbJenis() {
        cbJenis.removeAllItems();
        tambahItemComboBox(cbJenis, List.of("Pilih Jenis", "Metric", "Imperial"));

    }

    private void isi_cbJenisTujuan() {
        cbJenis1.removeAllItems();
        tambahItemComboBox(cbJenis1, List.of("Pilih Jenis", "Metric", "Imperial"));

    }

    private void isi_cbSatuan() {
        jenis = (String) cbJenis.getSelectedItem();
        cbSatuan.removeAllItems();
        cbSatuan.addItem("Pilih Satuan");

        if ("Metric".equals(jenis)) {
            isiSatuanMetric();
        } else if ("Imperial".equals(jenis)) {
            isiSatuanImperial();
        }
    }

    private void isi_cbSatuanTujuan() {
        jenis = (String) cbJenis1.getSelectedItem();
        cbSatuan1.removeAllItems();
        cbSatuan1.addItem("Pilih Satuan");

        if ("Metric".equals(jenis)) {
            isiSatuanMetricTujuan();
        } else if ("Imperial".equals(jenis)) {
            isiSatuanImperialTujuan();
        }
    }

    private void tambahItemComboBox(javax.swing.JComboBox<String> comboBox, List<String> items) {
        for (String item : items) {
            comboBox.addItem(item);
        }
    }


    private void btnBesaranTurunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBesaranTurunanActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        BesaranTurunan.setVisible(true);

    }//GEN-LAST:event_btnBesaranTurunanActionPerformed

    private void btnWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWaktuActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Waktu";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnWaktuActionPerformed

    private void btnBesaranPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBesaranPokokActionPerformed
        Home.setVisible(false);
        BesaranPokok.setVisible(true);
    }//GEN-LAST:event_btnBesaranPokokActionPerformed

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void btnBesaranTurunanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBesaranTurunanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBesaranTurunanMouseClicked

    private void btnBesaranPokokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBesaranPokokMouseClicked

    }//GEN-LAST:event_btnBesaranPokokMouseClicked

    private void btnWaktuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWaktuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWaktuMouseClicked

    private void btnPanjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanjangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanjangMouseClicked

    private void btnMassaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMassaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMassaMouseClicked

    private void btnSuhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuhuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuhuMouseClicked

    private void btnKuatArusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKuatArusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKuatArusMouseClicked

    private void btnIntensitasCahayaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntensitasCahayaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIntensitasCahayaMouseClicked

    private void btnJumlahZatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJumlahZatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJumlahZatMouseClicked

    private void btnPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanjangActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Panjang";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();

    }//GEN-LAST:event_btnPanjangActionPerformed

    private void btnMassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMassaActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Massa";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();

    }//GEN-LAST:event_btnMassaActionPerformed

    private void btnSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuhuActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Suhu";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnSuhuActionPerformed

    private void btnKuatArusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuatArusActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Kuat Arus";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnKuatArusActionPerformed

    private void btnIntensitasCahayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntensitasCahayaActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Intensitas Cahaya";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnIntensitasCahayaActionPerformed

    private void btnJumlahZatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJumlahZatActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Jumlah Zat";
        BesaranPokok.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnJumlahZatActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        BesaranPokok.setVisible(false);
        Home.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUsahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsahaActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Usaha";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnUsahaActionPerformed

    private void btnGayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGayaActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Gaya";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnGayaActionPerformed

    private void btnPercepatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercepatanActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Percepatan";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnPercepatanActionPerformed

    private void btnDayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayaActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Daya";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnDayaActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        BesaranTurunan.setVisible(false);
        Home.setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnKecepatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKecepatanActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Kecepatan";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
        System.out.println(besaranDipilih);
    }//GEN-LAST:event_btnKecepatanActionPerformed

    private void btnVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumeActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Volume";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnVolumeActionPerformed

    private void btnLuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuasActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Luas";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnLuasActionPerformed

    private void btnMassaJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMassaJenisActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Massa Jenis";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnMassaJenisActionPerformed

    private void btnMomentumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMomentumActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Momentum";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnMomentumActionPerformed

    private void btnTekananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTekananActionPerformed
        // TODO add your handling code here:
        besaranDipilih = "Tekanan";
        BesaranTurunan.setVisible(false);
        Konversi.setVisible(true);
        isi_cbJenis();
        isi_cbJenisTujuan();
    }//GEN-LAST:event_btnTekananActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        Konversi.setVisible(false);
        Home.setVisible(true);
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        History.setVisible(true);
        loadHistoryTable();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        // TODO add your handling code here:
        History.setVisible(false);
        Home.setVisible(true);
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
        isi_cbSatuan();
    }//GEN-LAST:event_cbJenisActionPerformed

    private void cbJenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenis1ActionPerformed
        // TODO add your handling code here:
        isi_cbSatuanTujuan();
    }//GEN-LAST:event_cbJenis1ActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        konversiSatuan();
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnTukarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTukarActionPerformed
        // TODO add your handling code here:
        String tempJenis = (String) cbJenis.getSelectedItem();
        String tempSatuan = (String) cbSatuan.getSelectedItem();

        cbJenis.setSelectedItem(cbJenis1.getSelectedItem());
        cbSatuan.setSelectedItem(cbSatuan1.getSelectedItem());

        cbJenis1.setSelectedItem(tempJenis);
        cbSatuan1.setSelectedItem(tempSatuan);
    }//GEN-LAST:event_btnTukarActionPerformed

    private void btnKonversiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKonversiKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnKonversiKeyPressed

    private void taInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taInputActionPerformed
        // TODO add your handling code here:
        konversiSatuan();
    }//GEN-LAST:event_taInputActionPerformed

    private void btnBack3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBack3KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBack3KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            // Hapus data dari history
            history.deleteData(selectedRow);

            // Muat ulang tabel
            loadHistoryTable();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String besaran = (String) jTable1.getValueAt(selectedRow, 0);
            double nilaiInput = (double) jTable1.getValueAt(selectedRow, 1); 
            String satuanAsal = (String) jTable1.getValueAt(selectedRow, 2);
            String satuanTujuan = (String) jTable1.getValueAt(selectedRow, 3);
            double hasilKonversi = (double) jTable1.getValueAt(selectedRow, 4);

            besaran = JOptionPane.showInputDialog(this, "Edit Besaran:", besaran);
            nilaiInput = Double.parseDouble(JOptionPane.showInputDialog(this, "Edit Nilai Input:", nilaiInput));
            satuanAsal = JOptionPane.showInputDialog(this, "Edit Satuan Asal:", satuanAsal);
            satuanTujuan = JOptionPane.showInputDialog(this, "Edit Satuan Tujuan:", satuanTujuan);
            hasilKonversi = Double.parseDouble(JOptionPane.showInputDialog(this, "Edit Hasil Konversi:", hasilKonversi));

            history.updateData(selectedRow, besaran, nilaiInput, satuanAsal, satuanTujuan, hasilKonversi);
            loadHistoryTable();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diedit.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String besaran = JOptionPane.showInputDialog(this, "Masukkan Besaran:");
        double nilaiInput = Double.parseDouble(JOptionPane.showInputDialog(this, "Masukkan Nilai Input:"));
        String satuanAsal = JOptionPane.showInputDialog(this, "Masukkan Satuan Asal:");
        String satuanTujuan = JOptionPane.showInputDialog(this, "Masukkan Satuan Tujuan:");
        double hasilKonversi = Double.parseDouble(JOptionPane.showInputDialog(this, "Masukkan Hasil Konversi:"));

        history.addData(besaran, nilaiInput, satuanAsal, satuanTujuan, hasilKonversi);
        loadHistoryTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BesaranPokok;
    private javax.swing.JPanel BesaranTurunan;
    private javax.swing.JPanel History;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Konversi;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBesaranPokok;
    private javax.swing.JButton btnBesaranTurunan;
    private javax.swing.JButton btnDaya;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGaya;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnIntensitasCahaya;
    private javax.swing.JButton btnJumlahZat;
    private javax.swing.JButton btnKecepatan;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JButton btnKuatArus;
    private javax.swing.JButton btnLuas;
    private javax.swing.JButton btnMassa;
    private javax.swing.JButton btnMassaJenis;
    private javax.swing.JButton btnMomentum;
    private javax.swing.JButton btnPanjang;
    private javax.swing.JButton btnPercepatan;
    private javax.swing.JButton btnSuhu;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTekanan;
    private javax.swing.JButton btnTukar;
    private javax.swing.JButton btnUsaha;
    private javax.swing.JButton btnVolume;
    private javax.swing.JButton btnWaktu;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbJenis1;
    private javax.swing.JComboBox<String> cbSatuan;
    private javax.swing.JComboBox<String> cbSatuan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField taInput;
    private javax.swing.JTextField taOutput;
    // End of variables declaration//GEN-END:variables

}
